"""added services

Revision ID: 54a82c4d037b
Revises: b4dfdc37b172
Create Date: 2023-03-15 14:26:01.894487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a82c4d037b'
down_revision = 'b4dfdc37b172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
