"""initial

Revision ID: a4cd877a089e
Revises: b4dfdc37b172
Create Date: 2023-03-21 10:05:31.701113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cd877a089e'
down_revision = 'b4dfdc37b172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('articles_updated_by_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_created_by_fkey', 'articles', type_='foreignkey')
    op.alter_column('companies', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('companies', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('companies_updated_by_fkey', 'companies', type_='foreignkey')
    op.drop_constraint('companies_created_by_fkey', 'companies', type_='foreignkey')
    op.alter_column('entities_legal', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entities_legal', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('entities_legal_updated_by_fkey', 'entities_legal', type_='foreignkey')
    op.drop_constraint('entities_legal_created_by_fkey', 'entities_legal', type_='foreignkey')
    op.alter_column('users', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('users_updated_by_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_created_by_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_created_by_fkey', 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key('users_updated_by_fkey', 'users', 'users', ['updated_by'], ['id'])
    op.alter_column('users', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('entities_legal_created_by_fkey', 'entities_legal', 'users', ['created_by'], ['id'])
    op.create_foreign_key('entities_legal_updated_by_fkey', 'entities_legal', 'users', ['updated_by'], ['id'])
    op.alter_column('entities_legal', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entities_legal', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('companies_created_by_fkey', 'companies', 'users', ['created_by'], ['id'])
    op.create_foreign_key('companies_updated_by_fkey', 'companies', 'users', ['updated_by'], ['id'])
    op.alter_column('companies', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('companies', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('articles_created_by_fkey', 'articles', 'users', ['created_by'], ['id'])
    op.create_foreign_key('articles_updated_by_fkey', 'articles', 'users', ['updated_by'], ['id'])
    op.alter_column('articles', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('articles', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
