"""added mixinchanges

Revision ID: b4dfdc37b172
Revises: b4eca8c249ce
Create Date: 2023-03-15 08:36:21.129578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dfdc37b172'
down_revision = 'b4eca8c249ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('articles', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('updated_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'articles', 'users', ['updated_by'], ['id'])
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('companies', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('updated_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'companies', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'companies', 'users', ['created_by'], ['id'])
    op.add_column('entities_legal', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('entities_legal', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('entities_legal', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('entities_legal', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('entities_legal', sa.Column('updated_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'entities_legal', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'entities_legal', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'entities_legal', type_='foreignkey')
    op.drop_constraint(None, 'entities_legal', type_='foreignkey')
    op.drop_column('entities_legal', 'updated_by')
    op.drop_column('entities_legal', 'created_by')
    op.drop_column('entities_legal', 'is_deleted')
    op.drop_column('entities_legal', 'updated_at')
    op.drop_column('entities_legal', 'created_at')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'updated_by')
    op.drop_column('companies', 'created_by')
    op.drop_column('companies', 'is_deleted')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'updated_by')
    op.drop_column('articles', 'created_by')
    op.drop_column('articles', 'is_deleted')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
