"""init

Revision ID: b4eca8c249ce
Revises: 
Create Date: 2023-03-15 08:34:41.667139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4eca8c249ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities_legal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_legal', sa.String(length=50), nullable=True),
    sa.Column('tin', sa.Integer(), nullable=True),
    sa.Column('name_bank', sa.String(length=50), nullable=True),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('apartment', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities_legal_to_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_company', sa.Integer(), nullable=False),
    sa.Column('id_entity_legal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['id_entity_legal'], ['entities_legal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_first', sa.String(length=50), nullable=True),
    sa.Column('name_middle', sa.String(length=50), nullable=True),
    sa.Column('name_last', sa.String(length=50), nullable=True),
    sa.Column('id_company', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('entities_legal_to_companies')
    op.drop_table('entities_legal')
    op.drop_table('companies')
    op.drop_table('articles')
    # ### end Alembic commands ###
